--------------------------------------------------------
--  文件已创建 - 星期六-十二月-09-2017   
--------------------------------------------------------
DROP TABLE "CRM"."CONSULTRECORD" cascade constraints;
DROP TABLE "CRM"."CUSTOMER" cascade constraints;
DROP TABLE "CRM"."CUSTOMERINFO" cascade constraints;
DROP TABLE "CRM"."DEPARTMENT" cascade constraints;
DROP TABLE "CRM"."EMPLOYEE" cascade constraints;
DROP TABLE "CRM"."JOBINFO" cascade constraints;
DROP TABLE "CRM"."JOBRIGHT" cascade constraints;
DROP TABLE "CRM"."RESETPASS" cascade constraints;
DROP TABLE "CRM"."RIGHTS" cascade constraints;
DROP SEQUENCE "CRM"."SEQ_CONREC_ID";
DROP SEQUENCE "CRM"."SEQ_CUSINFO_ID";
DROP SEQUENCE "CRM"."SEQ_CUS_ID";
DROP SEQUENCE "CRM"."SEQ_EMP_ID";
DROP SEQUENCE "CRM"."SEQ_JOBRIG_ID";
DROP SEQUENCE "CRM"."SEQ_REG_ID";
DROP SEQUENCE "CRM"."SEQ_REPASS_ID";
DROP SEQUENCE "CRM"."SER_DEPT_ID";
DROP SEQUENCE "CRM"."SER_JOBINFO_ID";
--------------------------------------------------------
--  DDL for Table CONSULTRECORD
--------------------------------------------------------

  CREATE TABLE "CRM"."CONSULTRECORD" 
   (	"ID" NUMBER(11,0), 
	"CUSTOMERID" NUMBER(11,0), 
	"CONSULTMANID" NUMBER(11,0), 
	"CONSULTSTATU" VARCHAR2(2 BYTE), 
	"CONSULTDATE" TIMESTAMP (6), 
	"RESULT" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "CRM"."CONSULTRECORD"."CUSTOMERID" IS '客户编号 对应客户表主键';
   COMMENT ON COLUMN "CRM"."CONSULTRECORD"."CONSULTMANID" IS '咨询师编号 对应员工表主键';
   COMMENT ON COLUMN "CRM"."CONSULTRECORD"."CONSULTSTATU" IS '咨询状态  0：新增 1：紧跟 2：已报名
3：死单(死单时同时更新客户基础信息表状态)
4报名后退费';
   COMMENT ON COLUMN "CRM"."CONSULTRECORD"."CONSULTDATE" IS '咨询日期   分配到的日期';
   COMMENT ON COLUMN "CRM"."CONSULTRECORD"."RESULT" IS '咨询备注';
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "CRM"."CUSTOMER" 
   (	"ID" NUMBER(11,0), 
	"NAME" VARCHAR2(30 BYTE), 
	"EDUCATION" VARCHAR2(20 BYTE), 
	"PHONENO" VARCHAR2(11 BYTE), 
	"QQ" NUMBER(11,0), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"CUSTOMSTATU" VARCHAR2(2 BYTE), 
	"CREATEDATE" TIMESTAMP (6), 
	"INVITENAME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "CRM"."CUSTOMER"."EDUCATION" IS '教育水平';
   COMMENT ON COLUMN "CRM"."CUSTOMER"."CUSTOMSTATU" IS '客户状态:0 新增未上门 1新增已上门 2：销售跟进中 3：咨询跟进中 4：死单 5：已报名 ';
   COMMENT ON COLUMN "CRM"."CUSTOMER"."INVITENAME" IS '邀请人姓名  网咨员工添加时，将自己的名字加进去';
--------------------------------------------------------
--  DDL for Table CUSTOMERINFO
--------------------------------------------------------

  CREATE TABLE "CRM"."CUSTOMERINFO" 
   (	"ID" NUMBER(11,0), 
	"CUSTOMERID" NUMBER(11,0), 
	"FOLLOWMANID" NUMBER(11,0), 
	"STATU" VARCHAR2(2 BYTE), 
	"STARTDATE" TIMESTAMP (6), 
	"LASTFOLLOWDATE" TIMESTAMP (6), 
	"PLANDATE" TIMESTAMP (6), 
	"MARK" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "CRM"."CUSTOMERINFO"."CUSTOMERID" IS '客户编号   对应客户表主键';
   COMMENT ON COLUMN "CRM"."CUSTOMERINFO"."FOLLOWMANID" IS '跟单人编号  对应员工表主键';
   COMMENT ON COLUMN "CRM"."CUSTOMERINFO"."STATU" IS '跟单状态   0：未联系 1：未接通
2：紧跟 3：已上门4：死单(死单时同时更新客户基础信息表状态)，5：电话无效';
   COMMENT ON COLUMN "CRM"."CUSTOMERINFO"."STARTDATE" IS '开始日期  分配到的日期';
   COMMENT ON COLUMN "CRM"."CUSTOMERINFO"."LASTFOLLOWDATE" IS '最近联系';
   COMMENT ON COLUMN "CRM"."CUSTOMERINFO"."PLANDATE" IS '计划联系日期';
   COMMENT ON COLUMN "CRM"."CUSTOMERINFO"."MARK" IS '跟单备注';
--------------------------------------------------------
--  DDL for Table DEPARTMENT
--------------------------------------------------------

  CREATE TABLE "CRM"."DEPARTMENT" 
   (	"ID" NUMBER(11,0), 
	"DNAME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "CRM"."DEPARTMENT"."ID" IS '部门编号';
   COMMENT ON COLUMN "CRM"."DEPARTMENT"."DNAME" IS '部门名称';
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "CRM"."EMPLOYEE" 
   (	"ID" NUMBER(10,0), 
	"USERNAME" VARCHAR2(30 BYTE), 
	"PASS" VARCHAR2(18 BYTE), 
	"NICKNAME" VARCHAR2(30 BYTE), 
	"REALNAME" VARCHAR2(30 BYTE), 
	"JOBINFOID" NUMBER(11,0), 
	"DEPARTMENTID" NUMBER(11,0), 
	"PHONENO" VARCHAR2(11 BYTE), 
	"OFFICETEL" VARCHAR2(11 BYTE), 
	"WORKSTATU" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "CRM"."EMPLOYEE"."USERNAME" IS '邮箱作为用户名';
   COMMENT ON COLUMN "CRM"."EMPLOYEE"."NICKNAME" IS '昵称';
   COMMENT ON COLUMN "CRM"."EMPLOYEE"."REALNAME" IS '真实姓名';
   COMMENT ON COLUMN "CRM"."EMPLOYEE"."JOBINFOID" IS '对应职位表主键';
   COMMENT ON COLUMN "CRM"."EMPLOYEE"."DEPARTMENTID" IS '对应部门表主键';
   COMMENT ON COLUMN "CRM"."EMPLOYEE"."OFFICETEL" IS '办公电话';
--------------------------------------------------------
--  DDL for Table JOBINFO
--------------------------------------------------------

  CREATE TABLE "CRM"."JOBINFO" 
   (	"ID" NUMBER(11,0), 
	"JOB" VARCHAR2(30 BYTE), 
	"DEPARTMENTID" NUMBER(11,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "CRM"."JOBINFO"."JOB" IS '职位名称';
   COMMENT ON COLUMN "CRM"."JOBINFO"."DEPARTMENTID" IS '部门编号';
--------------------------------------------------------
--  DDL for Table JOBRIGHT
--------------------------------------------------------

  CREATE TABLE "CRM"."JOBRIGHT" 
   (	"ID" NUMBER(11,0), 
	"JOBINFOID" NUMBER(11,0), 
	"RIGHTID" NUMBER(11,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "CRM"."JOBRIGHT"."JOBINFOID" IS '职位编号   对应职位表主键';
   COMMENT ON COLUMN "CRM"."JOBRIGHT"."RIGHTID" IS '权限编号   对应权限表主键';
--------------------------------------------------------
--  DDL for Table RESETPASS
--------------------------------------------------------

  CREATE TABLE "CRM"."RESETPASS" 
   (	"ID" NUMBER(11,0), 
	"USERNAME" VARCHAR2(30 BYTE), 
	"PHONENO" VARCHAR2(11 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RIGHTS
--------------------------------------------------------

  CREATE TABLE "CRM"."RIGHTS" 
   (	"RID" NUMBER(11,0), 
	"RIGHTNAME" VARCHAR2(40 BYTE), 
	"RIGHTTYPE" VARCHAR2(2 BYTE), 
	"URL" VARCHAR2(30 BYTE), 
	"PID" NUMBER(11,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "CRM"."RIGHTS"."RIGHTNAME" IS '权限名称';
   COMMENT ON COLUMN "CRM"."RIGHTS"."RIGHTTYPE" IS '权限级别 1表示一级权限2表示二级权限，二级权限才有实际的功能';
   COMMENT ON COLUMN "CRM"."RIGHTS"."URL" IS '选项卡url值  权限功能打开选项卡时选项卡中include的JSP页面名称';
   COMMENT ON COLUMN "CRM"."RIGHTS"."PID" IS '类别编号  一级权限pid和自身的rid相同，二级权限是其对应的一级权限的rid';
--------------------------------------------------------
--  DDL for Sequence SEQ_CONREC_ID
--------------------------------------------------------

   CREATE SEQUENCE  "CRM"."SEQ_CONREC_ID"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CUSINFO_ID
--------------------------------------------------------

   CREATE SEQUENCE  "CRM"."SEQ_CUSINFO_ID"  MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CUS_ID
--------------------------------------------------------

   CREATE SEQUENCE  "CRM"."SEQ_CUS_ID"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_EMP_ID
--------------------------------------------------------

   CREATE SEQUENCE  "CRM"."SEQ_EMP_ID"  MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_JOBRIG_ID
--------------------------------------------------------

   CREATE SEQUENCE  "CRM"."SEQ_JOBRIG_ID"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_REG_ID
--------------------------------------------------------

   CREATE SEQUENCE  "CRM"."SEQ_REG_ID"  MINVALUE 1 MAXVALUE 999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_REPASS_ID
--------------------------------------------------------

   CREATE SEQUENCE  "CRM"."SEQ_REPASS_ID"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SER_DEPT_ID
--------------------------------------------------------

   CREATE SEQUENCE  "CRM"."SER_DEPT_ID"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SER_JOBINFO_ID
--------------------------------------------------------

   CREATE SEQUENCE  "CRM"."SER_JOBINFO_ID"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
REM INSERTING into CRM.CONSULTRECORD
SET DEFINE OFF;
REM INSERTING into CRM.CUSTOMER
SET DEFINE OFF;
REM INSERTING into CRM.CUSTOMERINFO
SET DEFINE OFF;
REM INSERTING into CRM.DEPARTMENT
SET DEFINE OFF;
REM INSERTING into CRM.EMPLOYEE
SET DEFINE OFF;
REM INSERTING into CRM.JOBINFO
SET DEFINE OFF;
REM INSERTING into CRM.JOBRIGHT
SET DEFINE OFF;
REM INSERTING into CRM.RESETPASS
SET DEFINE OFF;
REM INSERTING into CRM.RIGHTS
SET DEFINE OFF;
Insert into CRM.RIGHTS (RID,RIGHTNAME,RIGHTTYPE,URL,PID) values (4,'销售主管
','1',null,4);
Insert into CRM.RIGHTS (RID,RIGHTNAME,RIGHTTYPE,URL,PID) values (5,'普通销售','2',null,4);
Insert into CRM.RIGHTS (RID,RIGHTNAME,RIGHTTYPE,URL,PID) values (6,'咨询主管','1',null,6);
Insert into CRM.RIGHTS (RID,RIGHTNAME,RIGHTTYPE,URL,PID) values (7,'普通咨询','2',null,6);
--------------------------------------------------------
--  DDL for Index JOBINFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CRM"."JOBINFO_PK" ON "CRM"."JOBINFO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CUSTOM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CRM"."CUSTOM_PK" ON "CRM"."CUSTOMER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CRM"."EMPLOYEE_PK" ON "CRM"."EMPLOYEE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index JOBRIGHT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CRM"."JOBRIGHT_PK" ON "CRM"."JOBRIGHT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESETPASS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CRM"."RESETPASS_PK" ON "CRM"."RESETPASS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DEPARTMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CRM"."DEPARTMENT_PK" ON "CRM"."DEPARTMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CONSULTRECORD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CRM"."CONSULTRECORD_PK" ON "CRM"."CONSULTRECORD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CUSTOMINFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CRM"."CUSTOMINFO_PK" ON "CRM"."CUSTOMERINFO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RIGHTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CRM"."RIGHTS_PK" ON "CRM"."RIGHTS" ("RID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table JOBRIGHT
--------------------------------------------------------

  ALTER TABLE "CRM"."JOBRIGHT" ADD CONSTRAINT "JOBRIGHT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CRM"."JOBRIGHT" MODIFY ("RIGHTID" NOT NULL ENABLE);
  ALTER TABLE "CRM"."JOBRIGHT" MODIFY ("JOBINFOID" NOT NULL ENABLE);
  ALTER TABLE "CRM"."JOBRIGHT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "CRM"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CRM"."EMPLOYEE" MODIFY ("WORKSTATU" NOT NULL ENABLE);
  ALTER TABLE "CRM"."EMPLOYEE" MODIFY ("OFFICETEL" NOT NULL ENABLE);
  ALTER TABLE "CRM"."EMPLOYEE" MODIFY ("PHONENO" NOT NULL ENABLE);
  ALTER TABLE "CRM"."EMPLOYEE" MODIFY ("DEPARTMENTID" NOT NULL ENABLE);
  ALTER TABLE "CRM"."EMPLOYEE" MODIFY ("JOBINFOID" NOT NULL ENABLE);
  ALTER TABLE "CRM"."EMPLOYEE" MODIFY ("REALNAME" NOT NULL ENABLE);
  ALTER TABLE "CRM"."EMPLOYEE" MODIFY ("NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "CRM"."EMPLOYEE" MODIFY ("PASS" NOT NULL ENABLE);
  ALTER TABLE "CRM"."EMPLOYEE" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "CRM"."EMPLOYEE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "CRM"."CUSTOMER" ADD CONSTRAINT "CUSTOM_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CRM"."CUSTOMER" MODIFY ("QQ" NOT NULL ENABLE);
  ALTER TABLE "CRM"."CUSTOMER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "CRM"."CUSTOMER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RIGHTS
--------------------------------------------------------

  ALTER TABLE "CRM"."RIGHTS" ADD CONSTRAINT "RIGHTS_PK" PRIMARY KEY ("RID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CRM"."RIGHTS" MODIFY ("PID" NOT NULL ENABLE);
  ALTER TABLE "CRM"."RIGHTS" MODIFY ("RIGHTTYPE" NOT NULL ENABLE);
  ALTER TABLE "CRM"."RIGHTS" MODIFY ("RIGHTNAME" NOT NULL ENABLE);
  ALTER TABLE "CRM"."RIGHTS" MODIFY ("RID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "CRM"."DEPARTMENT" ADD CONSTRAINT "DEPARTMENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CRM"."DEPARTMENT" MODIFY ("DNAME" NOT NULL ENABLE);
  ALTER TABLE "CRM"."DEPARTMENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CUSTOMERINFO
--------------------------------------------------------

  ALTER TABLE "CRM"."CUSTOMERINFO" MODIFY ("STARTDATE" NOT NULL ENABLE);
  ALTER TABLE "CRM"."CUSTOMERINFO" ADD CONSTRAINT "CUSTOMINFO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CRM"."CUSTOMERINFO" MODIFY ("STATU" NOT NULL ENABLE);
  ALTER TABLE "CRM"."CUSTOMERINFO" MODIFY ("FOLLOWMANID" NOT NULL ENABLE);
  ALTER TABLE "CRM"."CUSTOMERINFO" MODIFY ("CUSTOMERID" NOT NULL ENABLE);
  ALTER TABLE "CRM"."CUSTOMERINFO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table JOBINFO
--------------------------------------------------------

  ALTER TABLE "CRM"."JOBINFO" ADD CONSTRAINT "JOBINFO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CRM"."JOBINFO" MODIFY ("DEPARTMENTID" NOT NULL ENABLE);
  ALTER TABLE "CRM"."JOBINFO" MODIFY ("JOB" NOT NULL ENABLE);
  ALTER TABLE "CRM"."JOBINFO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONSULTRECORD
--------------------------------------------------------

  ALTER TABLE "CRM"."CONSULTRECORD" ADD CONSTRAINT "CONSULTRECORD_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CRM"."CONSULTRECORD" MODIFY ("CONSULTDATE" NOT NULL ENABLE);
  ALTER TABLE "CRM"."CONSULTRECORD" MODIFY ("CONSULTSTATU" NOT NULL ENABLE);
  ALTER TABLE "CRM"."CONSULTRECORD" MODIFY ("CONSULTMANID" NOT NULL ENABLE);
  ALTER TABLE "CRM"."CONSULTRECORD" MODIFY ("CUSTOMERID" NOT NULL ENABLE);
  ALTER TABLE "CRM"."CONSULTRECORD" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESETPASS
--------------------------------------------------------

  ALTER TABLE "CRM"."RESETPASS" ADD CONSTRAINT "RESETPASS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CRM"."RESETPASS" MODIFY ("PHONENO" NOT NULL ENABLE);
  ALTER TABLE "CRM"."RESETPASS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "CRM"."RESETPASS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CONSULTRECORD
--------------------------------------------------------

  ALTER TABLE "CRM"."CONSULTRECORD" ADD CONSTRAINT "CONSULTRECORD_CUS_FK" FOREIGN KEY ("CUSTOMERID")
	  REFERENCES "CRM"."CUSTOMER" ("ID") ENABLE;
  ALTER TABLE "CRM"."CONSULTRECORD" ADD CONSTRAINT "CONSULTRECORD_EMP_FK" FOREIGN KEY ("CONSULTMANID")
	  REFERENCES "CRM"."EMPLOYEE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CUSTOMERINFO
--------------------------------------------------------

  ALTER TABLE "CRM"."CUSTOMERINFO" ADD CONSTRAINT "CUSTOMINFO_CUS_FK" FOREIGN KEY ("CUSTOMERID")
	  REFERENCES "CRM"."CUSTOMER" ("ID") ENABLE;
  ALTER TABLE "CRM"."CUSTOMERINFO" ADD CONSTRAINT "CUSTOMINFO_EMP_FK" FOREIGN KEY ("FOLLOWMANID")
	  REFERENCES "CRM"."EMPLOYEE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "CRM"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_DEP_FK" FOREIGN KEY ("DEPARTMENTID")
	  REFERENCES "CRM"."DEPARTMENT" ("ID") ENABLE;
  ALTER TABLE "CRM"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_JOB_FK" FOREIGN KEY ("JOBINFOID")
	  REFERENCES "CRM"."JOBINFO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table JOBINFO
--------------------------------------------------------

  ALTER TABLE "CRM"."JOBINFO" ADD CONSTRAINT "JOBINFO_DEP_FK" FOREIGN KEY ("DEPARTMENTID")
	  REFERENCES "CRM"."DEPARTMENT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table JOBRIGHT
--------------------------------------------------------

  ALTER TABLE "CRM"."JOBRIGHT" ADD CONSTRAINT "JOBRIGHT_JOBINFO_FK" FOREIGN KEY ("JOBINFOID")
	  REFERENCES "CRM"."JOBINFO" ("ID") ENABLE;
  ALTER TABLE "CRM"."JOBRIGHT" ADD CONSTRAINT "JOBRIGHT_RIGHTS_FK" FOREIGN KEY ("RIGHTID")
	  REFERENCES "CRM"."RIGHTS" ("RID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RIGHTS
--------------------------------------------------------

  ALTER TABLE "CRM"."RIGHTS" ADD CONSTRAINT "RIGHTS_SELF_FK" FOREIGN KEY ("PID")
	  REFERENCES "CRM"."RIGHTS" ("RID") ENABLE;
